openapi: "3.0.0"
info:
  version: 1.0.0
  title: Test api
  description: OpenAPI 3.0 specification of shaman API
paths:
  /:
    get:
      description: foo
      responses:
        200:
          description: foo
          content:
            application/json:
              schema:
                type: object
                required: [foo]
                properties:
                  foo: { type: string }
            text/plain: {}
  /entities/{id}:
    get:
      description: get entity
      parameters:
        - name: id
          in: path
          schema: { type: integer }
      responses:
        200:
          description: entity
          content:
            application/json:
              schema:
                type: object
                required: [entity]
                properties:
                  entity:
                    type: object
                    required: [id]
                    properties:
                      id: { type: integer }

